import base64
import http.client
import json
import ssl
import struct
import tempfile
import threading
import time
import unittest
import zipfile
from pathlib import Path
from urllib.parse import urlencode
from unittest.mock import patch

from bbm.config import validate_origin
from bbm.metadata import METADATA_ENTRY, BOOTSTRAP_URLS, literals, patch_bootstrap
from bbm.protocol import Codec, ProtocolError, redact
from bbm.server import Application, make_server
from bbm.state import State

ROOT = Path(__file__).resolve().parents[1]


class ProtocolTests(unittest.TestCase):
    def setUp(self):
        self.codec = Codec(b"test-signing-key", b"0123456789abcdef")

    def test_independent_dotnet_fixture(self):
        # Generated by tools/protocol_reference using System.Security.Cryptography.
        form = b"bbmPacket=Kpc87sZQP8ZxVhrhSfwqeau6OVCX91rq3%2BaRtuhedYClM3tK0%2FKEZH%2Br1jVeYKKLHiBavgdxcKmMzk7TNIT1P4lIIgqZVhIUnuMnGUHlUbxTSNeeubDNBhHmDwhqzNL4kxyhzJPx4xAUiBKPYCNyfw1Zz%2BI6iSnDOv%2FlEyb5ny3%2BV9taqqWpsqS0Eg9i2KQhL9ghlUXU3OMy7%2F%2B3rEl8ejdyIuBhqSTFkc2cJ%2BoWPtQ%3D"
        packet, wire = self.codec.decode(form, "application/x-www-form-urlencoded")
        self.assertEqual(packet, {"userId": 7, "sessionId": 11, "txId": 3})
        self.assertEqual(wire, "bbmPacket")

    def test_plain_bootstrap_form(self):
        packet, wire = self.codec.decode(b"jsonPacket=%7B%7D", "application/x-www-form-urlencoded; charset=UTF-8")
        self.assertEqual((packet, wire), ({}, "jsonPacket"))

    def test_signature_required(self):
        other = Codec(b"wrong-signing-key", b"0123456789abcdef")
        with self.assertRaises(ProtocolError):
            self.codec.decode(other.encode({"userId": 1}), "application/x-www-form-urlencoded")

    def test_expired_packet_rejected(self):
        with self.assertRaises(ProtocolError):
            self.codec.decode(self.codec.encode({}, expires=time.time()-3600), "application/x-www-form-urlencoded")

    def test_malformed_forms_rejected(self):
        for body in (b"jsonPacket=[]", b"jsonPacket={}&jsonPacket={}", b"bbmPacket=broken", b"jsonPacket={}&bbmPacket=x", b"jsonPacket=null"):
            with self.subTest(body=body), self.assertRaises(ProtocolError):
                self.codec.decode(body, "application/x-www-form-urlencoded")

    def test_redaction(self):
        self.assertEqual(redact({"nested": {"sessionId": 99, "accessToken": "secret"}, "txId": 3}),
                         {"nested": {"sessionId": "<redacted>", "accessToken": "<redacted>"}, "txId": 3})


class StateTests(unittest.TestCase):
    def test_persistence_bad_token_and_session_rotation(self):
        with tempfile.TemporaryDirectory() as tmp:
            path = Path(tmp)/"state.db"
            first = State(path)
            account = first.create()
            second = State(path)
            self.assertTrue(second.exists(account["udid"]))
            self.assertIsNone(second.login(account["udid"], "wrong"))
            session1 = second.login(account["udid"], account["accessToken"])
            self.assertTrue(first.valid_session(session1["userId"], session1["sessionId"]))
            session2 = first.login(account["udid"], account["accessToken"])
            self.assertFalse(second.valid_session(session1["userId"], session1["sessionId"]))
            self.assertTrue(second.valid_session(session2["userId"], session2["sessionId"]))
            self.assertFalse(second.valid_session(session2["userId"], 2**70))

    def test_dev_login_and_persisted_wallet(self):
        with tempfile.TemporaryDirectory() as tmp:
            path = Path(tmp)/"state.db"
            state = State(path, {"coin": 500, "candy": 500})
            session1 = state.login_dev("local-device")
            self.assertEqual(state.wallet(session1["userId"])["coin"], 500)
            state.set_wallet(session1["userId"], {"coin": 1234, "cash": 9})
            session2 = State(path, {"coin": 9999}).login_dev("local-device")
            self.assertEqual(session1["userId"], session2["userId"])
            self.assertEqual(state.wallet(session1["userId"])["coin"], 1234)
            self.assertEqual(state.wallet(session1["userId"])["cash"], 9)
            with self.assertRaises(ValueError):
                state.set_wallet(session1["userId"], {"coin": -1})


class ConfigTests(unittest.TestCase):
    def test_valid_origin(self):
        self.assertEqual(validate_origin("https://192.168.1.2:9200/"), "https://192.168.1.2:9200")

    def test_invalid_origin(self):
        for url in ("https://0.0.0.0:9100", "https://user:pass@example.org", "file:///tmp", "https://example.org/path", "https://example.org:99999", "https://example.org:0"):
            with self.subTest(url=url), self.assertRaises(ValueError):
                validate_origin(url)


@unittest.skipUnless((ROOT/"analysis/xapk_1.4.1/net.commseed.bbm.apk").is_file(), "Requires local source APK")
class ClientPatchTests(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        with zipfile.ZipFile(ROOT/"analysis/xapk_1.4.1/net.commseed.bbm.apk") as src:
            cls.blob = src.read(METADATA_ENTRY)

    def test_real_metadata_patch_changes_only_three_literals(self):
        original = literals(self.blob)
        output, report = patch_bootstrap(self.blob, "https://10.0.2.2:9200")
        changed = [(a.index, a.value, b.value) for a, b in zip(original, literals(output)) if a.value != b.value]
        self.assertEqual(len(changed), 3)
        self.assertEqual({a.decode() for _, a, _ in changed}, set(BOOTSTRAP_URLS))
        self.assertEqual({b for _, _, b in changed}, {b"https://10.0.2.2:9200"})
        self.assertEqual(len(output), len(self.blob))
        allowed = set()
        for item in report:
            old = original[item["literal_index"]]
            allowed.update(range(old.offset, old.offset+old.size))
            allowed.update(range(old.table_offset, old.table_offset+4))
        self.assertTrue(all(i in allowed for i, (a,b) in enumerate(zip(self.blob, output)) if a != b))

    def test_long_url_rejected(self):
        with self.assertRaises(ValueError):
            patch_bootstrap(self.blob, "https://"+"a"*50+":9100")

    def test_modified_source_rejected(self):
        with self.assertRaises(ValueError):
            patch_bootstrap(self.blob[:-1]+bytes([self.blob[-1]^1]), "https://127.0.0.1:9100")


@unittest.skipUnless((ROOT/".local/server.json").is_file(), "Run tools.prepare_local first")
class HttpsIntegrationTests(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        cls.tmp = tempfile.TemporaryDirectory()
        config = json.loads((ROOT/".local/server.json").read_text())
        config.update({"listen_host": "127.0.0.1", "listen_port": 0,
                       "database": str(Path(cls.tmp.name)/"state.db"),
                       "request_log": str(Path(cls.tmp.name)/"requests.jsonl")})
        cls.app = Application(config)
        cls.server = make_server(config, cls.app)
        cls.port = cls.server.server_address[1]
        cls.app.origin = f"https://127.0.0.1:{cls.port}"
        cls.ctx = ssl.create_default_context(cafile=str(ROOT/config["tls_cert"]))
        cls.thread = threading.Thread(target=cls.server.serve_forever, daemon=True)
        cls.thread.start()

    @classmethod
    def tearDownClass(cls):
        cls.server.shutdown()
        cls.server.server_close()
        cls.thread.join()
        cls.tmp.cleanup()

    def request(self, path, packet=None, plain=False):
        conn = http.client.HTTPSConnection("127.0.0.1", self.port, context=self.ctx)
        try:
            if packet is None:
                conn.request("GET", path)
            else:
                body = urlencode({"jsonPacket": json.dumps(packet)}).encode() if plain else self.app.codec.encode(packet)
                conn.request("POST", path, body=body, headers={"Content-Type": "application/x-www-form-urlencoded"})
            response = conn.getresponse()
            return response.status, response.read()
        finally:
            conn.close()

    def post(self, path, packet, plain=False):
        status, data = self.request(path, packet, plain)
        self.assertEqual(status, 200, data)
        return json.loads(data)

    def test_bootstrap_matches_real_field_names_and_local_addresses(self):
        res = self.post("/GetServerInfo", {}, plain=True)
        self.assertEqual(res["result"], 1)
        self.assertFalse(res["maintenanceInfo"]["isTerminatedBBM"])
        for env in ("Main", "Review"):
            self.assertEqual(set(res["serverInfo"][env]["url"].values()), {self.app.origin})
            self.assertEqual(res["serverInfo"][env]["aos"]["BundleVersion"], 240)

    def test_create_login_ping_and_unsupported_gameplay(self):
        account = self.post("/CreateUser", {"osType": 0, "dui": "test-device"})
        self.assertEqual(self.post("/IsLoginAble", {"udid": account["udid"]})["result"], 1)
        self.assertEqual(self.post("/LoginUser", {"udid": account["udid"], "accessToken": "wrong"})["result"], -112)
        login = self.post("/LoginUser", {"udid": account["udid"], "accessToken": account["accessToken"]})
        session = login["sessionInfo"]
        packet = {"userId": session["userId"], "sessionId": session["sessionId"], "txId": 7}
        self.assertEqual(self.post("/Ping", packet)["txId"], 7)
        self.assertEqual(self.post("/TxBuyItemStoreItem", packet)["result"], -205)
        self.assertEqual(self.post("/GetChatServerInfo", packet)["result"], -5001)
        self.assertEqual(self.post("/Ping", {**packet, "sessionId": 1})["result"], -910011)
        text = self.app.log_path.read_text()
        self.assertNotIn(account["accessToken"], text)
        self.assertNotIn(account["udid"], text)

    def test_dev_login_and_initial_read_model_chain(self):
        login = self.post("/Login", {"osType": 0, "dui": "test-device", "udid": "dev-device"})
        session = login["sessionInfo"]
        packet = {"userId": session["userId"], "sessionId": session["sessionId"], "txId": 10}
        info = self.post("/GetUserInfo", packet)
        self.assertEqual(info["userInfo"]["userId"], session["userId"])
        wallet = self.post("/GetUserWalletInfo", packet)
        self.assertEqual(wallet["userWalletInfo"]["coin"], 500)
        self.assertEqual(wallet["userWalletInfo"]["candy"], 500)
        self.assertEqual(self.post("/GetUserEquipInfo", packet)["userEquipInfo"]["monsterDeckId"], 0)
        inventory = self.post("/GetUserMonsterInventory", packet)
        self.assertEqual(len(inventory["userMonsterList"]), 3)
        town = self.post("/GetUserTownMapInfo", {**packet, "targetUserId": session["userId"]})
        self.assertEqual(town["townMapInfo"]["userID"], session["userId"])
        self.assertEqual(town["townMapInfo"]["coin"], 500)
        self.assertEqual(self.post("/GetUserStoreInfoList", packet)["userItemStoreInfoList"], [])
        self.assertEqual(self.post("/GetUserTutorialList", packet)["lstCompletedTutorialId"], [])
        self.assertEqual(self.post("/GetUserShield", packet)["shieldLimitTime"], 0)

    def test_plain_game_packets_rejected(self):
        status, _ = self.request("/CreateUser", {}, plain=True)
        self.assertEqual(status, 400)

    def test_manifest_download_and_path_traversal(self):
        status, body = self.request("/bundles/patch_result.json")
        self.assertEqual(status, 200)
        self.assertEqual(len(json.loads(body)["patchResults"]), 305)
        for path in ("/bundles/../server.json", "/bundles/%2e%2e%2fserver.json", "/bundles/..%5cserver.json", "/not-implemented"):
            self.assertEqual(self.request(path)[0], 404)


if __name__ == "__main__":
    unittest.main()
